//
// Created by laurent on 30/05/25.
//

#ifndef TRANSLATE_HORIZONTAL_INPUT_TO_DESIRED_VEL_SYSTEM_H
#define TRANSLATE_HORIZONTAL_INPUT_TO_DESIRED_VEL_SYSTEM_H

#endif //TRANSLATE_HORIZONTAL_INPUT_TO_DESIRED_VEL_SYSTEM_H
