//
// Created by laurent on 30/05/25.
//

#ifndef TRANSLATE_VERTICAL_INPUT_TO_DESIRED_VEL_SYSTEM_H
#define TRANSLATE_VERTICAL_INPUT_TO_DESIRED_VEL_SYSTEM_H

#endif //TRANSLATE_VERTICAL_INPUT_TO_DESIRED_VEL_SYSTEM_H
